services:
  - type: web
    name: dashboard-cupons-saojoao
    runtime: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VTEX_ACCOUNT
        value: sjdigital
      - key: VTEX_APP_KEY
        value: vtexappkey-sjdigital-NBIBYX
      - key: VTEX_APP_TOKEN
        value: FMNZUETMELXKBOSLMUVZKXCHVBSGIZOPKZDTNWFECKBNISTKJABVJIALYEYPWIEGJTBNJFTFIOXRTKHIFXSMOFIJOXFDNWWCTUBMFLFRYRPZDBNWMZRQFIAABGXNSJNO
